# Generated by Django 4.0 on 2022-01-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculate_conveyor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultCalculate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название конвейера')),
                ('capacity', models.FloatField(verbose_name='Полученная производительность, т/ч')),
                ('speed', models.FloatField(verbose_name='Скорость конвейера, м/с')),
                ('speed_max', models.FloatField(verbose_name='Максимальная скорость конвейера, м/с')),
                ('angle_conveyor', models.FloatField(verbose_name='Угол конвейера в градусах')),
                ('angle_conveyor_max', models.FloatField(verbose_name='Допустимый угол ковнейера в градусах')),
                ('angle_phi', models.FloatField(verbose_name='Угол естественного откоса материала в градусах')),
                ('width_frame', models.IntegerField(verbose_name='Ширина рамы в мм')),
                ('belt_width', models.IntegerField(verbose_name='Ширина ленты в мм')),
                ('count_gasket', models.IntegerField(verbose_name='Количество тяговых прокладок, шт')),
                ('k_p', models.IntegerField(verbose_name='Прочность тяговых прокладок')),
                ('distance_idlers', models.FloatField(verbose_name='Расстояние между верхними роликоопорами в м')),
                ('distance_idlers_down', models.FloatField(verbose_name='Расстояние между нижними роликоопорами в м')),
                ('diameter_rollers', models.IntegerField(verbose_name='Диаметр роликов в мм')),
                ('drive_drum_diameter', models.IntegerField(verbose_name='Диаметр приводного барабана в мм')),
                ('driven_drum', models.IntegerField(verbose_name='Диаметр натяжного/ведомого барабана в мм')),
                ('revolving_drum', models.IntegerField(verbose_name='Диаметр обводящего барабана в мм')),
                ('deflecting_drum', models.IntegerField(verbose_name='Диаметр отклоняющего барабана в мм')),
                ('shaft_drive_drum', models.IntegerField(verbose_name='Диаметр вала приводного барабана в мм')),
                ('motor_power_calc', models.IntegerField(verbose_name='Мощность мотор-редуктора в кВт')),
                ('brake', models.IntegerField(verbose_name='Крутящий момент на выходном валу мотор-редуктора в Нм')),
                ('tension_length', models.IntegerField(verbose_name='Частота вращения выходного вала редуктора в об/мин')),
                ('torque', models.CharField(max_length=50, verbose_name='Тормоз')),
                ('rotation_speed_drive_drum', models.IntegerField(verbose_name='Ход натяжного устройства в мм')),
            ],
            options={
                'verbose_name': 'Результат',
                'verbose_name_plural': 'Результаты',
            },
        ),
    ]
